"""init2

Revision ID: 082c79c67211
Revises: f3eeb2e43a65
Create Date: 2023-05-30 19:49:12.496018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '082c79c67211'
down_revision = 'f3eeb2e43a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS buisiness_entities')
    op.alter_column('category', 'rars',
               existing_type=postgresql.ENUM('0+', '6+', '18+', '16+', '12+', name='rars_t', schema='buisiness_entities'),
               nullable=True,
               comment='Age constraint',
               existing_comment='Title of the category',
               schema='buisiness_entities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'rars',
               existing_type=postgresql.ENUM('0+', '6+', '18+', '16+', '12+', name='rars_t', schema='buisiness_entities'),
               nullable=False,
               comment='Title of the category',
               existing_comment='Age constraint',
               schema='buisiness_entities')
    op.execute('DROP SCHEMA IF EXISTS buisiness_entities RESTRICT')
    # ### end Alembic commands ###
